version: '3.5'
services:
  postgres:
    image: postgres
    command: postgres -c 'max_connections=450'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    network_mode: host
    ports:
      - 5432:5432
    volumes:
      - ../create-db.sql:/docker-entrypoint-initdb.d/create-db.sql

  app:
    build: .
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - PORT=3001
    restart: on-failure
    network_mode: host
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '4'
